### ISSUE TITLE
Credit line is not deisgned

### ISSUE THREAD

**Issue by zohar** [linnovate/da11y#3]
The credit line (back to Linnovate) is ...ugly .
It should be smaller, with better proportions and spacing. 

Try something like:

``` css
#da11y-credits {
        font-size: 65% !important;
}
#da11y-credits hr {
    margin-top: 5px;
    margin-bottom: 5px;
}
```

<img width="162" alt="fullscreen-2" src="https://cloud.githubusercontent.com/assets/109613/17476312/af97579e-5d5f-11e6-9129-21b602e2781f.png">
